### PR TITLE
feat: change css to allow color picker selector to show (refs #634)

### PR DESCRIPTION
**Pull request by adeptflax**
### Please check if the PR fulfills these requirements

- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has description for the breaking change

### Description
This pull request changes the css so that the color slider from the color picker shows up. It would make it easier for people to select colors. I'm not sure why this was hidden. I had to add some css to make it show up correctly. 

#### Before:
color-before

#### After:

color-after

### CODE REVIEW

**Comment by adeptflax** [comment]
I realized a bug in my commit. When there is an additional option in the color picker. The color slider doesn't render correctly.

### closed
image


### expanded
 
image

**Comment by adeptflax** [comment]
Just noticed the color picker div isn't in the correct position when expanded.

**Comment by lja1018** [comment]
@adeptflax 
Thank you for the PR.
Can you fix the colors slider so that they are properly rendered?

**Comment by adeptflax** [comment]
@lja1018 yeah, I was going to do that. I'm going to work on it now.

**Comment by adeptflax** [comment]
Would It be better if the color picker expanded below the activation button and hide the arrow or expanded upward or something else?

**Comment by adeptflax** [comment]
https://github.com/nhn/tui.image-editor/blob/master/apps/image-editor/src/js/ui/filter.js#L418
https://github.com/nhn/tui.image-editor/blob/master/apps/image-editor/src/js/ui/filter.js#L443

Commenting out these lines, fixes the weird rending issues.

**Comment by adeptflax** [comment]
image

how it looks now.

**Comment by adeptflax** [comment]
Expanding upward seems like the better idea, I'll see if I can get that working.

**Comment by adeptflax** [comment]
I think the color slider should be moved above the color pallet.

**Comment by lja1018** [comment]
@adeptflax 
Does it mean that the colour slider expands up, not down?

**Comment by adeptflax** [comment]
@lja1018 I meant the color picker box expands downward.

**Comment by adeptflax** [comment]
ok got it fixed. I added an option to set the opacity of the draw tool

**Comment by lja1018** [comment]
@adeptflax 
Thank you for the PR.
It will take some time because a detailed review is needed as it can affect usability.

**Comment by adeptflax** [comment]
# New Filter UI:

image

## Things I changed:

- Added more filters.
- Remove redundant filters. I added Tint to the blend filter. I remove multiply because it was just an option in the blend filter. Color Filter and Remove White where the same filter, except color filter tried to use the alpha channel on "removeColor", which isn't supported on fabric yet.  
-  add numerical input to filter values
-  I made it so filter are always processed in a consistent order. In the current version depending on the order on which you selected the filters the image will look differently. It redid it in a similar way as this [fabric.js example](http://fabricjs.com/image-filters) 

## Other

The filter code was really badly written. I'll fix the conflicts and update the tests later. I will be adding more features in the coming weeks.

**Comment by dadlaniTarun** [comment]
@adeptflax is there any update regarding this PR???

**Pull request closed without merging**
