### PR TITLE
feat: Added ability to allow developers to change colour palette preset

### PR DESCRIPTION
**Pull request by marcodafonseca**
Added ability to allow developers to change colour palette preset
feat: Customize default colour palette (#481)

feat: #481

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has description for the breaking change

### Description
Added ability to allow developers to change colour palette preset

When constructing the ImageEditor a developer can now pass through their own colour palette if they don't want to use the preset one.

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

**Comment by marcodafonseca** [comment]
Is this PR ever going to get some kind of attention or feedback? My clients really need this feature

**Comment by JohntheFish** [comment]
I came across this PR because it is functionality I would like to use. 
What happens if the initial colour of any tool is not in the palette?
Should the PR also include settings for initial colour of tools?
How would such work with any other tool initialisation options (such options don't exist yet, but maybe could in the future)?

**Comment by lja1018** [comment]
@marcodafonseca @JohntheFish 
Sorry for late reply. We will update as soon as possible.

**Comment by JohntheFish** [comment]
bump

**Comment by marcodafonseca** [comment]
+1

**Comment by JohntheFish** [comment]
bump again

**Comment by marcodafonseca** [comment]
Bump

**Comment by JohntheFish** [comment]
bump

**Pull request closed without merging**
